### ISSUE TITLE
依赖注入

### ISSUE THREAD

**Issue by overtalk** [darjun/go-daily-lib#1]
刚刚看了你写的有关如何使用 dig 的博客，google 推出了一个不使用反射的依赖注入库，希望博主可以也出一篇介绍，期待！
https://github.com/google/wire

**Comment by darjun** [comment]
我了解一下😀

**Comment by darjun** [comment]
[https://juejin.im/post/5e5d2e85e51d4527214bb9d9](https://juejin.im/post/5e5d2e85e51d4527214bb9d9)，还请不吝赐教😀
