### ISSUE TITLE
数据验证

### ISSUE THREAD

**Issue by overtalk** [darjun/go-daily-lib#10]
https://github.com/go-ozzo/ozzo-validation
这个库主要用于数据验证，检查数据是否符合预设定的规则，一般可以用于配置的检测等

**Comment by darjun** [comment]
已加入 todo list

**Comment by darjun** [comment]
掘金：https://juejin.cn/post/6976378694231130120/
segmentfault：https://segmentfault.com/a/1190000040214453
知乎：https://zhuanlan.zhihu.com/p/382774369
个人博客：https://darjun.github.io/2021/06/20/godailylib/ozzo-validation/

欢迎关注公众号 GoUpUp～
