### ISSUE TITLE
Watermill

### ISSUE THREAD

**Issue by pnpdb** [darjun/go-daily-lib#12]
看了您了解到Watermill这个包，但如果我想有多个订阅者订阅同一个topic，那么多个订阅者都会消费这个消息，有没有办法只有一个订阅者消费这个消息，不重复消费...    谢谢!

**Comment by darjun** [comment]
watermill没有提供这个机制，需要自己在应用层实现了

**Comment by lesismal** [comment]
可以试试我这个，看到你这种需求，刚加了个PublishToOne，可能是节点订阅但是只想单节点执行任务吧？

https://github.com/lesismal/achan

发布的地方用

```golang
c.PublishToOne(...)
```
