### ISSUE TITLE
关于cron中的chan

### ISSUE THREAD

**Issue by zackzhangkai** [darjun/go-daily-lib#16]
关于cron中的以下代码：
```
func SkipIfStillRunning(logger Logger) JobWrapper {
  return func(j Job) Job {
    var ch = make(chan struct{}, 1)
    ch <- struct{}{}
    return FuncJob(func() {
      select {
      case v := <-ch:
        j.Run()
        ch <- v
      default:
        logger.Info("skip")
      }
    })
  }
}
```
其中：`    ch <- struct{}{}` struct初始化不是应该是`ch <- struct{}`吗，为什么是`ch <- struct{}{}`？

**Comment by dreamer2q** [comment]
go的语法就是这样的

`struct{}` 表示声明结构体的类型(尽管里面什么都没有)，后面加上`{}`才表示初始化一个这样的结构体。

如果是C语言的话,直接使用`{}`即可。

**Comment by darjun** [comment]
struct{}表示的是一个空结构体类型，再加上{}才是初始化
简单点说`struct{}`是类型，`struct{}{}`是值，你不能发送类型到channel中，只能发送值
