### ISSUE TITLE
gojsonq 翻页查询偏移量问题

### ISSUE THREAD

**Issue by JokerDevops** [darjun/go-daily-lib#2]
你好，我在使用 gojsonq 的时候发现没有偏移量 Offset 这个方法了。
部分代码如下，没有 Offset 方法，请问你用的是那个版本的 gojsonq
```
r1 := gq.From("items").Select("id", "name").Limit(3).Get()
```

**Comment by darjun** [comment]
最新的代码，我看了下，还是有的哦，看这里→[https://github.com/thedevsaddam/gojsonq/blob/50f4fe8a3e4b1e535a61b51b75d3c74adf29f70a/jsonq.go#L172](https://github.com/thedevsaddam/gojsonq/blob/50f4fe8a3e4b1e535a61b51b75d3c74adf29f70a/jsonq.go#L172)
