### ISSUE TITLE
终端UI库 bubbletea

### ISSUE THREAD

**Issue by kiyonlin** [darjun/go-daily-lib#22]
非常炫酷的终端UI库 [bubbletea](https://github.com/charmbracelet/bubbletea)

![](https://camo.githubusercontent.com/8ea80aa68d31e09192f1dcce27d262b358dcf346/68747470733a2f2f73747566662e636861726d2e73682f627562626c657465612f627562626c657465612d6578616d706c652e676966)

**Comment by darjun** [comment]
我前几天也看到了，安排上！

**Comment by darjun** [comment]
@kiyonlin 已完成

segmentfault: [https://segmentfault.com/a/1190000040179971](https://segmentfault.com/a/1190000040179971)
juejin:  [https://juejin.cn/post/6974164916366213151/](https://juejin.cn/post/6974164916366213151/]

公众号：GoUpUp
欢迎关注
