### ISSUE TITLE
golang代码生成器库

### ISSUE THREAD

**Issue by kiyonlin** [darjun/go-daily-lib#3]
这个 [代码生成器库](https://github.com/dave/jennifer) 也蛮有趣的

**Comment by darjun** [comment]
棒棒棒，已加入todo list

**Comment by darjun** [comment]
请指教哈😄
[https://juejin.im/post/5e6cec36e51d4526e2629a71](https://juejin.im/post/5e6cec36e51d4526e2629a71)
