### ISSUE TITLE
公众号文章纠错

### ISSUE THREAD

**Issue by panjf2000** [darjun/go-daily-lib#30]
今天碰巧看到你写的介绍 `ants` 的[公众号文章](https://mp.weixin.qq.com/s/ysG0q9LIYgWHIoY_LK-W9A)，写的不错。

不过，文章结尾的 `ants` Github 链接错写成了 github.com/valyala/ants，正确的地址应该是 github.com/panjf2000/ants，因为你的公众号没有评论功能，所以到这里来反馈一下。

**Comment by darjun** [comment]
> 今天碰巧看到你写的介绍 `ants` 的[公众号文章](https://mp.weixin.qq.com/s/ysG0q9LIYgWHIoY_LK-W9A)，写的不错。
> 
> 不过，文章结尾的 `ants` Github 链接错写成了 github.com/valyala/ants，正确的地址应该是 github.com/panjf2000/ants，因为你的公众号没有评论功能，所以到这里来反馈一下。

被大佬回复了好激动。公众号文章发布了就不能修改了，我其他平台上的链接已经修改过来了

**Comment by panjf2000** [comment]
公众号文章发布后不是可以修改最多 20 个错别字？

**Comment by darjun** [comment]
> 公众号文章发布后不是可以修改最多 20 个错别字？

咦，这样嘛。我晚上回去看看，涨姿势了😄

**Comment by darjun** [comment]
@panjf2000 多谢大佬提点，已修改

**Comment by panjf2000** [comment]
再接再厉，继续产出优质文章~
