### ISSUE TITLE
有哪个库能根据数据库表生成对应结构体的吗

### ISSUE THREAD

**Issue by cpj555** [darjun/go-daily-lib#34]
有哪个库能根据数据库表生成对应结构体的吗

**Comment by yezihack** [comment]
> 有哪个库能根据数据库表生成对应结构体的吗

https://github.com/yezihack/go-mygen

**Comment by cpj555** [comment]
> > 有哪个库能根据数据库表生成对应结构体的吗
> 
> https://github.com/yezihack/go-mygen

好的 我看看

**Comment by darjun** [comment]
> 有哪个库能根据数据库表生成对应结构体的吗

看看sqlc呢，https://darjun.github.io/2020/04/28/godailylib/sqlc/

**Comment by cpj555** [comment]
https://github.com/xxjwxc/gormt  用了这个,能满足我的需求- -
