### ISSUE TITLE
每日一库推荐 - go-queue

### ISSUE THREAD

**Issue by czasg** [darjun/go-daily-lib#41]
https://github.com/czasg/go-queue
基于 Go 实现的 内存/磁盘 队列，支持 FIFO、LIFO、Priority。

**Comment by darjun** [comment]
已加todolist，感谢推荐👍

**Comment by dinglizhi** [comment]
> 已加todolist，感谢推荐👍

好久没更新了啊
![图片](https://user-images.githubusercontent.com/59157933/145590893-9d6f2583-a611-442c-a12d-f597f9108ce5.png)

**Comment by darjun** [comment]
> > 已加todolist，感谢推荐👍
> 
> 好久没更新了啊 ![图片](https://user-images.githubusercontent.com/59157933/145590893-9d6f2583-a611-442c-a12d-f597f9108ce5.png)

最近几个月忙到生活无法自理😂
