### ISSUE TITLE
struct拷贝

### ISSUE THREAD

**Issue by thinkgos** [darjun/go-daily-lib#5]
相同struct数据合并的mergo，不同struct数据的copier库考虑下呗。 要是有更好的也推荐下，目前就找到这两。
要是权限库casbin能考虑更好了

**Comment by darjun** [comment]
casbin已经在todo list中了。
mergo和copier我了解一下哈

**Comment by thinkgos** [comment]
[https://github.com/imdario/mergo](url)
[https://github.com/jinzhu/copier](url)

**Comment by darjun** [comment]
老哥请指教
mergo：https://juejin.im/post/5e6a3aace51d450edd292e81
copier：https://juejin.im/post/5e6b81e551882549281c08c1
