### ISSUE TITLE
共享内存

### ISSUE THREAD

**Issue by overtalk** [darjun/go-daily-lib#6]
大佬又是我哈哈哈！
想请教大佬一个问题，就是 golang 中使用共享内存的库有什么推荐的吗？
在网上没有找到合适的库，最好是shm+mmap都有的那种

**Comment by darjun** [comment]
我留意一下哈，印象中没有比较合适的😀

**Comment by overtalk** [comment]
好的，谢谢大佬了

**Comment by darjun** [comment]
客气了，我不是大佬/(ㄒoㄒ)/~~
