### ISSUE TITLE
相等比较库

### ISSUE THREAD

**Issue by thinkgos** [darjun/go-daily-lib#8]
大佬也是勤奋，博客让人受益良多。推一个常用库吧，go-cmp，google出品必属精品，项目上用，真是太强大了，完美go哲学。
地址 https://github.com/google/go-cmp

**Comment by darjun** [comment]
666，已加入todo list👍

**Comment by darjun** [comment]
老哥，请指教😄
[https://juejin.im/post/5e75db44f265da57480f609c](https://juejin.im/post/5e75db44f265da57480f609c)
